## Referances
1 : https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html#the-basics

2 : http://cs231n.github.io/python-numpy-tutorial/

3 : https://github.com/jrjohansson/scientific-python-lectures

4 : https://github.com/tpcarneiro/Python-Data-Science-and-Machine-Learning-Bootcamp

5 : https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists

In [2]:
import numpy as np
# from numpy import *

In [3]:
python_list = [[1,2,3,4,5], [6,7,8,9,10]]

arr = np.array(python_list) 

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr = np.arange(0, 20 , 2)

arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros((4,3) , dtype = "int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((4,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((4,3) , 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [10]:
np.full((5,6) , "biplob")

array([['biplob', 'biplob', 'biplob', 'biplob', 'biplob', 'biplob'],
       ['biplob', 'biplob', 'biplob', 'biplob', 'biplob', 'biplob'],
       ['biplob', 'biplob', 'biplob', 'biplob', 'biplob', 'biplob'],
       ['biplob', 'biplob', 'biplob', 'biplob', 'biplob', 'biplob'],
       ['biplob', 'biplob', 'biplob', 'biplob', 'biplob', 'biplob']],
      dtype='<U6')

In [11]:
#For Creating Identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [14]:
#import matplotlib.pyplot as plt
#var = np.linspace(0,1000,9)
#print(var)
#plt.hist(var)

np.linspace(0,1000,9)

array([   0.,  125.,  250.,  375.,  500.,  625.,  750.,  875., 1000.])

In [15]:
np.logspace(0,10,7,base=np.e)  #epsilon

array([1.00000000e+00, 5.29449005e+00, 2.80316249e+01, 1.48413159e+02,
       7.85771994e+02, 4.16026201e+03, 2.20264658e+04])

In [16]:
np.logspace(0,100,8)  #Default 10 base log

array([1.00000000e+000, 1.93069773e+014, 3.72759372e+028, 7.19685673e+042,
       1.38949549e+057, 2.68269580e+071, 5.17947468e+085, 1.00000000e+100])

In [17]:
np.logspace(1,20,4, base=np.e)

array([2.71828183e+00, 1.53047486e+03, 8.61703624e+05, 4.85165195e+08])

In [18]:
#For Creating diagonal matrix
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [19]:
np.diag([3,5,2,8])

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 8]])

In [20]:
#uniform distributed number
np.random.rand(2,2,2)

array([[[0.88241159, 0.4259069 ],
        [0.43014995, 0.85966776]],

       [[0.03859588, 0.94508345],
        [0.61008843, 0.63843392]]])

In [21]:
np.random.rand(5,6,2)

array([[[0.98391073, 0.02899304],
        [0.02220258, 0.77515051],
        [0.74790272, 0.14650282],
        [0.20438186, 0.91218836],
        [0.47777058, 0.19585821],
        [0.25983654, 0.5324499 ]],

       [[0.89135387, 0.28735543],
        [0.79143084, 0.46776882],
        [0.99215617, 0.09199058],
        [0.21795872, 0.61956785],
        [0.49134381, 0.82406822],
        [0.55831511, 0.94313177]],

       [[0.59321459, 0.16622118],
        [0.37712989, 0.74927236],
        [0.19747257, 0.11970183],
        [0.39044733, 0.21462662],
        [0.5153162 , 0.25764636],
        [0.51624557, 0.15895624]],

       [[0.83469021, 0.19962795],
        [0.07531457, 0.55953487],
        [0.930728  , 0.03830042],
        [0.15398503, 0.97448085],
        [0.70023092, 0.00136393],
        [0.24135467, 0.37773357]],

       [[0.40361714, 0.4811582 ],
        [0.93609903, 0.50750404],
        [0.60520179, 0.8918053 ],
        [0.60428104, 0.41783228],
        [0.1066275 , 0.72794339],
      

In [22]:
#standard normal distribution
np.random.randn(2,3)

array([[ 1.18503309,  0.21368123,  0.71494828],
       [ 0.62604004,  0.37062097, -1.06091653]])

In [23]:
np.random.randn(2,2,3)

array([[[-1.05579848,  1.65898215,  1.18767715],
        [-0.35452509,  0.42069798, -1.34003361]],

       [[ 1.24454916,  1.59950608,  0.47428972],
        [ 0.13622901, -0.93272407, -1.35159913]]])

In [24]:
np.random.randint(45,90, 10)

array([47, 53, 68, 55, 81, 62, 83, 74, 45, 53])

In [25]:
np.random.randint(23,45,5 , dtype="int64")

array([38, 41, 39, 32, 23], dtype=int64)

In [26]:
np.random.randint(0,10,(4,3))

array([[2, 0, 4],
       [4, 9, 3],
       [4, 7, 9],
       [8, 9, 3]])

In [27]:
arr = np.random.randint(0,10,(4,3))

In [28]:
print(arr)
arr.reshape(6,2)
#arr.reshape(5,5)

[[4 7 2]
 [2 6 2]
 [6 0 9]
 [5 6 4]]


array([[4, 7],
       [2, 2],
       [6, 2],
       [6, 0],
       [9, 5],
       [6, 4]])

In [29]:
arr = np.random.randint(0,100,(4,3))
print(arr)
print(arr.min())
print(arr.max())
print(arr.argmin())

[[42 22 98]
 [65 16 72]
 [77 61 82]
 [17 39 93]]
16
98
4


In [30]:

#arr = np.random.randint(12,50,10)
#print(arr)
#print(arr.max())
#print(arr.min())
#print(arr.argmax())  #max value position
#print(arr.argmin())  #min value position


In [31]:
arr.shape

(4, 3)

In [32]:
arr.ndim  #x axis y axis. find out dimension

2

In [33]:
arr.size  #Total element

12

In [34]:
arr = np.random.rand(4,3)
print(arr)
arr.dtype

[[0.45017601 0.47468824 0.48742594]
 [0.81971474 0.59562123 0.5938136 ]
 [0.96994218 0.33621011 0.56100564]
 [0.22294951 0.09933601 0.50986229]]


dtype('float64')

In [35]:
arr.itemsize

8

In [36]:
arr2 = arr #dont copy only pass the reference thats why there memory address are same...

print(arr.data)
print(arr2.data)

In [37]:
sample_arr = np.random.randint(0,100,10)

sample_arr

array([92, 39, 21, 98, 55, 64, 92, 73, 40, 77])

In [38]:
for data in sample_arr:
    print(data)

92
39
21
98
55
64
92
73
40
77


In [39]:
#for i in range(len(sample_arr)):
    #print(sample_arr)

for i in range(len(sample_arr)):
    print(sample_arr[i])

92
39
21
98
55
64
92
73
40
77


In [40]:
sample_arr[1:8:2]

array([39, 98, 64, 73])

In [41]:
print(sample_arr)
sample_arr[5:]

[92 39 21 98 55 64 92 73 40 77]


array([64, 92, 73, 40, 77])

In [42]:
arr = sample_arr.copy()

arr[:] = 1000

print(sample_arr)
print(arr)
print(sample_arr.data)
print(arr.data)

[92 39 21 98 55 64 92 73 40 77]
[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]


In [43]:
arr2d = np.random.randint(0,100,(5,5))

print(arr2d)



[[77 16 22 70 58]
 [17 49 53 80 55]
 [55 77 15 49  8]
 [20 48 49 84 50]
 [42 77 39 95 80]]


In [44]:
print(arr2d[1][4])

55


In [45]:
print(arr2d[1,4])

55


In [46]:
print(arr2d[:2,1:])  #row = :2  col = 1:

[[16 22 70 58]
 [49 53 80 55]]


In [47]:
print(arr2d[3:5,3:5])

[[84 50]
 [95 80]]


In [48]:
# print(arr2d)
arr2d[1:3,1:3]

array([[49, 53],
       [77, 15]])

In [49]:
arr = np.arange(0,11)
bool_arr = arr > 4

arr2 = arr[arr < 4]

arr2

array([0, 1, 2, 3])

In [50]:
arr = np.arange(0,11)

bool_arr = arr >= 4
print(bool_arr)

arr2 = arr[arr<4]
print(arr2)
print(arr)

[False False False False  True  True  True  True  True  True  True]
[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [54]:
arr1 = np.arange(1,13)
arr2 = np.arange(1,13)

print(arr1 + arr2)

print(arr1 / arr2)


[ 2  4  6  8 10 12 14 16 18 20 22 24]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [52]:
## https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [61]:
arr = np.arange(1,13).reshape(4,3)
arr2 = np.arange(1,13).reshape(4,3)

print(arr)
print(arr2)

print(arr * arr2)
print(arr + arr2)
print(arr - arr2)
print(arr / arr2)

print(np.add(arr,arr2))

print(np.max(arr))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
12
