In [19]:
import sys
sys.path.append('D:\ABC')

In [20]:
import Untitled as myfs

In [21]:
d = myfs.addAllNumerics(2,3,4,5,6,7)
print(d)

27


In [22]:
#from Untitled import addAllNumerics

In [23]:

#d = addAllNumerics(2,3,4,5,6,7)
##print(d)

In [24]:
myfs.myName

'Python Course'

In [25]:
def findMin(L,startIndx):
    m = L[startIndx]
    idx = startIndx    
    for i in range(startIndx,len(L)):
        x = L[i]
        if x<m:
            m = x
            idx = i
        else:
            pass                
    return m,idx

In [38]:
a,b = findMin([2,3,4,0,9],0)

In [39]:

def findMin(L,startIndx):
    m = L[startIndx]
    idx = startIndx    
    for i in range(startIndx,len(L)):
        x = L[i]
        if x<m:
            m = x
            idx = i
        else:
            pass                
    return m,idx

In [40]:
def swapValues(L,idx1,idx2):
    tmp = L[idx1]
    L[idx1] = L[idx2]
    L[idx2] = tmp
    return L

In [41]:
from Untitled import checkIfNotNumeric
def sortList(L):
    if not(checkIfNotNumeric(L)):
        print("Error: List does not contain numeric values")
        return
    else:
        c = 0
        for x in L:
            m,idx = findMin(L,c)
            L = swapValues(L,c,idx)
            c+=1
    return L

In [42]:
L2 = sortList([2,1,5,3,-8,17])
print(L2)

Error: List does not contain numeric values
None


In [1]:
L = [1,3,4.9,"name",3]
T = (1,3,4.9,"name",3)
S = {1,3,4.9,"name",3}
D = {23:"twothree",'B':43,'C':'CCD'}

In [2]:
print("The type of L is ", type(L))
print("The type of T is ", type(T))
print("The type of S is ", type(S))
print("The type of D is ", type(D))

The type of L is  <class 'list'>
The type of T is  <class 'tuple'>
The type of S is  <class 'set'>
The type of D is  <class 'dict'>


In [3]:
print(L[1])
print(T[1])
print(3 in S)
print(D[23])

3
3
True
twothree


In [4]:
L = L + ["how","are",6,"you"]

In [5]:
L

[1, 3, 4.9, 'name', 3, 'how', 'are', 6, 'you']

In [6]:
L.append("Biplob")

In [7]:
L

[1, 3, 4.9, 'name', 3, 'how', 'are', 6, 'you', 'Biplob']

In [8]:
T2 = ('a','b',45)
T3 = T+T2

In [9]:
T3

(1, 3, 4.9, 'name', 3, 'a', 'b', 45)

In [10]:
S.add(56)

In [11]:
S

{1, 3, 4.9, 56, 'name'}

In [12]:
S

{1, 3, 4.9, 56, 'name'}

In [13]:
S.update({233,"game",1})

In [14]:
S

{1, 233, 3, 4.9, 56, 'game', 'name'}

In [15]:
D

{23: 'twothree', 'B': 43, 'C': 'CCD'}

In [17]:
D["newKey"] = "NewValue"

In [18]:
D

{23: 'twothree', 'B': 43, 'C': 'CCD', 'newKey': 'NewValue'}

In [19]:
L

[1, 3, 4.9, 'name', 3, 'how', 'are', 6, 'you', 'Biplob']

In [20]:
del L[3]

In [21]:
L

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 'Biplob']

In [30]:
L2 = L.copy()

In [31]:
L2[2] = "four point nine"

In [35]:
L2 = L.copy()

In [36]:
L2

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 'Biplob']

In [37]:
L

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 'Biplob']

In [38]:
L

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 'Biplob']

In [39]:
L.clear?

In [40]:
L.pop?

In [41]:
L.reverse()

In [42]:
L

['Biplob', 'you', 6, 'are', 'how', 3, 4.9, 3, 1]

In [43]:
L[::-1]

[1, 3, 4.9, 3, 'how', 'are', 6, 'you', 'Biplob']

In [44]:
D.items()

dict_items([(23, 'twothree'), ('B', 43), ('C', 'CCD'), ('newKey', 'NewValue')])

In [45]:
D2 = {'A':L,'B':T,'C':S,'D':D}

In [46]:
D2['A']

['Biplob', 'you', 6, 'are', 'how', 3, 4.9, 3, 1]

In [47]:
D2['A'][3]

'are'

In [49]:
k = D2['D']

In [50]:
k

{23: 'twothree', 'B': 43, 'C': 'CCD', 'newKey': 'NewValue'}

In [53]:
for x in k:
    print(x,k[x])

23 twothree
B 43
C CCD
newKey NewValue


In [54]:
L3 = [L,T,D,23,"game"]

In [55]:
type(L3[2])

dict

In [56]:
type(L3[1])

tuple

In [57]:
type(L3[0])

list

In [58]:
L3 = [x**2 for x in range(10)]

In [60]:
L3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [61]:
S3 = {x**2 for x in range(2,20,3)}

In [62]:
S3

{4, 25, 64, 121, 196, 289}

In [1]:
def getDataFromUser():
    D = {}
    while True:
        studentId = input("Enter student ID: ")
        marksList = input("Enter the marks by comma separted values: ")
        moreStudents = input('Enter "no" to quit insertion: ')
        if studentId in D:
            print(studentId, "is already insterted")
        else:
            D[studentId] = marksList.split(",")
        if moreStudents.lower() == "no":
            return D

In [2]:
studentData = getDataFromUser()

Enter student ID: 12
Enter the marks by comma separted values: 44,56,34
Enter "no" to quit insertion: bf
Enter student ID: no
Enter the marks by comma separted values: 4,3,2
Enter "no" to quit insertion: no


In [3]:
studentData

{'12': ['44', '56', '34'], 'no': ['4', '3', '2']}

In [9]:
def getData():
    D = {}
    while True:
        studentId = input("Enter student ID: ")
        markList = input("Enter student mark list: ")
        moreStudents = input("Enter more student")
        
        if studentId in D:
            print(studentId , "is already insterted")
        else:
            D[studentId] = markList.split(",")
        if moreStudents.lower() == "no":
            return D

In [10]:
store = getData()

Enter student ID: 34
Enter student mark list: 45
Enter more student5
Enter student ID: 56,34,56
Enter student mark list: no
Enter more studentno


In [11]:
def getAvgMarks(D):
    avgMarks = {}
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s += int(marks)
        avgMarks[x] = s/len(L)
    return avgMarks

In [12]:
avgM = getAvgMarks(studentData)

In [13]:
avgM

{'12': 44.666666666666664, 'no': 3.0}

In [14]:
for x in avgM:
    print("Student :",x,"got avg Marks as: ",avgM[x])
    
for x in avgM:
    print("Student :", x , "got avg mark as: ", avgM[x])

Student : 12 got avg Marks as:  44.666666666666664
Student : no got avg Marks as:  3.0
Student : 12 got avg mark as:  44.666666666666664
Student : no got avg mark as:  3.0


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [16]:
import numpy as np

arr = np.array([23,4,34,5,435])

In [17]:
print(arr)

[ 23   4  34   5 435]


In [20]:
type(arr)

numpy.ndarray

In [21]:
print(np.__version__)

1.16.4


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
arra = np.array([34,4,5456,557])
print(arra)

[  34    4 5456  557]


In [25]:
print(type(arra))

<class 'numpy.ndarray'>


In [26]:
tupleArray = np.array((34,4,5,4,6))

In [27]:
print(tupleArray)

[34  4  5  4  6]


In [28]:
print(type(tupleArray))

<class 'numpy.ndarray'>


In [29]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [30]:
arr = np.array([2,3,4])
print(arr)

[2 3 4]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [32]:
print(arr[0])

[1 2 3]


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [34]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [36]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [37]:
print(arr[0][0])

[1 2 3]


In [38]:
print(arr.ndim)

3


In [43]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [44]:
arr[0]

array([[[[1, 2, 3, 4]]]])

In [50]:
arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [51]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [52]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1], arr.ndim)

2nd element on 1st dim:  2 2


In [53]:
arr[0, 1]

2

In [54]:
arr[1 , 4]

10

In [55]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [56]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [58]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [59]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [60]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [62]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [63]:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [64]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [65]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [5]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [13]:
C = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [20]:
C.shape[2]

3

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [25]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [30]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)
